openapi: "3.0.0"
x-api-id: "vet-store"
x-explorer-enabled: false
x-proxy-enabled: true
x-samples-enabled: true
info: 
  version: "1.0.0"
  title: "VetStore API"
security:
  - http: []
servers: 
  - 
    url: "https://example.com"
components:
  securitySchemes:
    http:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths: {}
